name: setup_env
description: Setup the environment in order to use Ariadne

runs:
  using: composite
  steps:
    - name: Install packages for building Ariadne
      shell: bash
      run: sudo apt-get install -y build-essential
                                   flex
                                   bison
                                   asciidoctor

    - name: Install Ruby plugins
      shell: bash
      run: sudo apt-get install -y ruby-asciidoctor-pdf
