name: setup_env
description: Setup the environment in order to use Ariadne

runs:
  using: composite
  steps:
    - name: Update the package manager to the latest info
      shell: bash
      run: sudo apt-get update

    - name: Test
      shell: bash
      run: |
        wget http://archive.ubuntu.com/ubuntu/pool/main/b/bison/libbison-dev_3.8.2+dfsg-1build1_amd64.deb
        wget http://archive.ubuntu.com/ubuntu/pool/main/b/bison/bison_3.8.2+dfsg-1build1_amd64.deb
        sudo dpkg -i libbison-dev_3.8.2+dfsg-1build1_amd64.deb
        sudo dpkg -i bison_3.8.2+dfsg-1build1_amd64.deb

    - name: Install packages for building Ariadne
      shell: bash
      run: sudo apt-get install -y build-essential
                                   python3-dev
                                   ruby-dev
                                   flex
                                   bison
                                   asciidoctor

    - name: Install Ruby plugins
      shell: bash
      run: sudo apt-get install -y ruby-asciidoctor-pdf
