name: Make an AppImage release of Ariadne

on: [push]
  #push:
  #  tags:
  #    - "RELEASE_V[0-9]+.[0-9]+.[0-9]+"
  # TODO set correct

jobs:

  #build_and_test:
  #  uses: ./.github/workflows/check_regression.yaml

  # The create-release job runs purely to initialize the GitHub release itself,
  # and names the release after the `RELEASE_Vx.y.z` tag that was pushed. It's
  # separate from building the release so that we only create the release once.
  create_release:
    name: create_release
      #needs: ["build_and_test"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Get the release version from the tag
        shell: bash
        run: echo "RELEASE_VERSION=RELEASE_V1.1.0" >> $GITHUB_ENV
        #run: echo "RELEASE_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
        # TODO set correct

      - name: Show the version
        shell: bash
        run: |
          echo "version is: $RELEASE_VERSION"

      - name: Create GitHub release
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create $RELEASE_VERSION
                               --verify-tag
                               --draft
                               --title $RELEASE_VERSION
                               --notes ""
        # TODO remove the draft

    outputs:
      version: ${{ env.RELEASE_VERSION }}


  build_release:
    name: build_release
    needs: ["create_release"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: ./.github/actions/setup_env/

      - name: Set the build directory for the packages
        shell: bash
        run: |
          package_build_dir="${{ github.workspace }}/package_build_dir"
          mkdir -p $package_build_dir
          echo "PACKAGE_BUILD_DIR=$package_build_dir" >> $GITHUB_ENV

      - name: Set the install directory for the packages
        shell: bash
        run: |
          package_install_dir="${{ github.workspace }}/package_install_dir"
          mkdir -p $package_install_dir
          echo "PACKAGE_INSTALL_DIR=$package_install_dir" >> $GITHUB_ENV

      - name: Set the version number for Python
        shell: bash
        run: echo "PYTHON_VERSION=3.10.12" >> $GITHUB_ENV

      - name: Install the Python package
        shell: bash
        run: |
          cd $PACKAGE_BUILD_DIR
          wget https://www.python.org/ftp/python/$PYTHON_VERSION/Python-$PYTHON_VERSION.tgz
          tar -zxf Python-$PYTHON_VERSION.tgz
          mkdir Python-$PYTHON_VERSION.build
          cd Python-$PYTHON_VERSION.build
          ../Python-$PYTHON_VERSION/configure --prefix=$PACKAGE_INSTALL_DIR/python/$PYTHON_VERSION --enable-shared --enable-optimizations
          make -j16
          make install

      - name: Update the PATH variable to use the new Python from now on
        shell: bash
        run: |
          echo "export PATH=$PACKAGE_INSTALL_DIR/python/$PYTHON_VERSION/bin:$PATH" >> $GITHUB_ENV
          echo "export LD_LIBRARY_PATH=$PACKAGE_INSTALL_DIR/python/$PYTHON_VERSION/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV

      - name: Set the version number for Ruby
        shell: bash
        run: |
          echo "RUBY_VERSION=2.6.10" >> $GITHUB_ENV
          echo "RUBY_VERSION_SHORT=2.6" >> $GITHUB_ENV

      - name: Install the Ruby package
        shell: bash
        run: |
          cd $PACKAGE_BUILD_DIR
          wget https://cache.ruby-lang.org/pub/ruby/$RUBY_VERSION_SHORT/ruby-$RUBY_VERSION.tar.gz
          tar -zxf ruby-$RUBY_VERSION.tar.gz
          mkdir ruby-$RUBY_VERSION.build
          cd ruby-$RUBY_VERSION.build
          ../ruby-$RUBY_VERSION/configure --prefix=$PACKAGE_INSTALL_DIR/ruby/$RUBY_VERSION --enable-shared
          make -j16
          make install

      - name: Update the PATH variable to use the new Ruby from now on
        shell: bash
        run: |
          echo "export PATH=$PACKAGE_INSTALL_DIR/ruby/$RUBY_VERSION/bin:$PATH" >> $GITHUB_ENV
          echo "export LD_LIBRARY_PATH=$PACKAGE_INSTALL_DIR/ruby/$RUBY_VERSION/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV

      - name: Configure CMake for Ariadne
        shell: bash
        run: MY_RUBY_HOME=$PACKAGE_INSTALL_DIR/ruby/$RUBY_VERSION
             Python_ROOT_DIR=$PACKAGE_INSTALL_DIR/python/$PYTHON_VERSION
             cmake -B $PACKAGE_BUILD_DIR/ariadne
                   -S ${{ github.workspace }}
                   -D SCRIPT_RUBY=ON
                   -D SCRIPT_PYTHON=ON
                   -D CMAKE_INSTALL_PREFIX=$PACKAGE_INSTALL_DIR/ariadne

      - name: Build Ariadne with CMake
        shell: bash
        run: cmake --build $PACKAGE_BUILD_DIR/ariadne
                   -j 16

      - name: Install Ariadne with CMake
        shell: bash
        run: cmake --install $PACKAGE_BUILD_DIR/ariadne

      - name: Extract the Ariadne version number
        shell: bash
        run: |
          ariadne_version=$(ls $PACKAGE_INSTALL_DIR/ariadne)
          echo "ARIADNE_VERSION=$ariadne_version" >> $GITHUB_ENV

      - name: Set the directory for creating the AppImage
        shell: bash
        run: |
          appimage_dir="${{ github.workspace }}/appimage_dir"
          mkdir -p $appimage_dir
          echo "APPIMAGE_DIR=$appimage_dir" >> $GITHUB_ENV

      - name: Copy the necessary GCC libs into the AppImage
        shell: bash
        run: |
          mkdir -p $APPIMAGE_DIR/gcc/lib64
          lib_file_path=$(gcc -print-file-name=libgcc_s.so)
          cp -a $lib_file_path $APPIMAGE_DIR/gcc/lib64
          lib_file_path=$(gcc -print-file-name=libgcc_s.so.1)
          cp -a $lib_file_path $APPIMAGE_DIR/gcc/lib64
          lib_file_path=$(gcc -print-file-name=libstdc++.so)
          cp -a $lib_file_path $APPIMAGE_DIR/gcc/lib64
          lib_file_path=$(gcc -print-file-name=libstdc++.so.6)
          cp -a ${lib_file_path}* $APPIMAGE_DIR/gcc/lib64

      - name: Copy the necessary Python libs into the AppImage
        shell: bash
        run: cp -a $PACKAGE_INSTALL_DIR/python $APPIMAGE_DIR

      - name: Copy the necessary Ruby libs into the AppImage
        shell: bash
        run: cp -a $PACKAGE_INSTALL_DIR/ruby $APPIMAGE_DIR

      - name: Copy the necessary Ariadne libs into the AppImage
        shell: bash
        run: cp -a $PACKAGE_INSTALL_DIR/ariadne $APPIMAGE_DIR

      - name: Create the AppRun script
        shell: bash
        run: |
          touch $APPIMAGE_DIR/AppRun
          echo "#! /bin/sh -e

          PREFIX=\$APPDIR
          export LD_LIBRARY_PATH=\$PREFIX/gcc/lib64
          export PATH=\$PREFIX/python/$PYTHON_VERSION/bin:\$PATH
          export LD_LIBRARY_PATH=\$PREFIX/python/$PYTHON_VERSION/lib:\$LD_LIBRARY_PATH
          export PATH=\$PREFIX/ruby/$RUBY_VERSION/bin:\$PATH
          export LD_LIBRARY_PATH=\$PREFIX/ruby/$RUBY_VERSION/lib:\$LD_LIBRARY_PATH
          export PATH=\$PREFIX/ariadne/$ARIADNE_VERSION/bin:\$PATH
          export PYTHONHOME=\$PREFIX/python/$PYTHON_VERSION

          ariadne \"\$@\"" > $APPIMAGE_DIR/AppRun

      - name: Make the AppRun script executable
        shell: bash
        run: chmod +x $APPIMAGE_DIR/AppRun

      - name: Create a desktop file for Ariadne
        shell: bash
        run: |
          touch $APPIMAGE_DIR/ariadne.desktop
          echo "[Desktop Entry]
          Name=ariadne
          Exec=ariadne
          Icon=ariadne_icon
          Type=Application
          Categories=Utility" > $APPIMAGE_DIR/ariadne.desktop

      - name: Copy an icon to the AppImage for Ariadne
        shell: bash
        run: cp doc/images/ariadne_icon.png $APPIMAGE_DIR/

      - name: Install packages for creating the AppImage
        shell: bash
        run: sudo apt-get install -y fuse
                                     libfuse2

      - name: Build the AppImage of Ariadne
        shell: bash
        run: |
          wget https://github.com/AppImage/AppImageKit/releases/download/13/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
          ARCH=x86_64 ./appimagetool-x86_64.AppImage $APPIMAGE_DIR
          echo "ARIADNE_APPIMAGE=ariadne-x86_64.AppImage" >> $GITHUB_ENV

      - name: Determine archive name
        shell: bash
        run: |
          version="${{ needs.create_release.outputs.version }}"
          echo "ARCHIVE=ariadne_$version" >> $GITHUB_ENV

      - name: Creating directory for the archive
        shell: bash
        run: |
          mkdir -p "$ARCHIVE"/{bin,doc}
          cp $ARIADNE_APPIMAGE "$ARCHIVE"/bin/
          cp -a ruby "$ARCHIVE"/
          cp README.md "$ARCHIVE"/
          cp gpl-3.0.html "$ARCHIVE"/
          cp doc/ariadne.adoc "$ARCHIVE"/doc/
          cp $PACKAGE_BUILD_DIR/ariadne/doc/ariadne.1 "$ARCHIVE"/doc/
          cp $PACKAGE_BUILD_DIR/ariadne/doc/ariadne.pdf "$ARCHIVE"/doc/
          cp $PACKAGE_BUILD_DIR/ariadne/doc/ariadne.html "$ARCHIVE"/doc/
          cp -a doc/images/ "$ARCHIVE"/doc/

      - name: Build archive (Unix)
        shell: bash
        run: |
          tar -czf "$ARCHIVE.tar.gz" "$ARCHIVE"
          shasum -a 256 "$ARCHIVE.tar.gz" > "$ARCHIVE.tar.gz.sha256"
          echo "ASSET=$ARCHIVE.tar.gz" >> $GITHUB_ENV
          echo "ASSET_SUM=$ARCHIVE.tar.gz.sha256" >> $GITHUB_ENV

      - name: Upload release archive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          version="${{ needs.create_release.outputs.version }}"
          gh release upload "$version" ${{ env.ASSET }} ${{ env.ASSET_SUM }}
